// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqpflhvwxwkadzminjhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxcGZsaHZ3eHdrYWR6bWluamhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODExODcsImV4cCI6MjA2NDQ1NzE4N30.wpfYD8iW9eL5WVrSHt5yXgeWQWBAAR3O32ddPNZmaHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);